// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4RuugnaT7I-A3Z3ZUNwTmVS228a2DrLw',
    appId: '1:185457198303:web:f5a49fcf2157c0b2b0156a',
    messagingSenderId: '185457198303',
    projectId: 'oudaounaoda',
    authDomain: 'oudaounaoda.firebaseapp.com',
    storageBucket: 'oudaounaoda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT9xzjGE4kb6PQAZz-KY7QYOxM2nK6Zi8',
    appId: '1:185457198303:android:830e9b283fb21bdab0156a',
    messagingSenderId: '185457198303',
    projectId: 'oudaounaoda',
    storageBucket: 'oudaounaoda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq4H5S2p9JcIRgERecPyb7UIAL5pi-8d8',
    appId: '1:185457198303:ios:094f7385b1dc4298b0156a',
    messagingSenderId: '185457198303',
    projectId: 'oudaounaoda',
    storageBucket: 'oudaounaoda.appspot.com',
    iosBundleId: 'com.example.plantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq4H5S2p9JcIRgERecPyb7UIAL5pi-8d8',
    appId: '1:185457198303:ios:094f7385b1dc4298b0156a',
    messagingSenderId: '185457198303',
    projectId: 'oudaounaoda',
    storageBucket: 'oudaounaoda.appspot.com',
    iosBundleId: 'com.example.plantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4RuugnaT7I-A3Z3ZUNwTmVS228a2DrLw',
    appId: '1:185457198303:web:5c46dd31ccb36ff7b0156a',
    messagingSenderId: '185457198303',
    projectId: 'oudaounaoda',
    authDomain: 'oudaounaoda.firebaseapp.com',
    storageBucket: 'oudaounaoda.appspot.com',
  );
}
